FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

ADD requirements.txt /tmp/

RUN apt update && apt install -y \
    build-essential \
    ffmpeg \
    libsm6 \
    libxext6 \
    git \
    vim \
    cmake \
    g++ \
    wget \
    libboost-all-dev \
    pkg-config \
    && conda install -c conda-forge pybind11

RUN conda create -n pogema python=3.10 -y \
    && conda run -n pogema pip install --no-cache-dir -r /tmp/requirements.txt \
    && conda run -n pogema pip install --no-cache-dir importlib-metadata==4.13.0 --force-reinstall

RUN wget -q https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz \
    && tar -xzf eigen-3.3.9.tar.gz \
    && mkdir -p eigen-3.3.9/build \
    && cd eigen-3.3.9/build \
    && cmake .. \
    && make install \
    && cd ../.. \
    && rm -rf eigen-3.3.9 eigen-3.3.9.tar.gz

RUN wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-1.14.1.tgz \
    && tar -xf onnxruntime-linux-x64-1.14.1.tgz \
    && cp onnxruntime-linux-x64-1.14.1/lib/* /usr/lib/ && cp onnxruntime-linux-x64-1.14.1/include/* /usr/include/

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate pogema && exec \"$@\"", "--"]
